spring:
  application:
    name: cdrGenerator

  sql:
    init:
      mode: never

  datasource:
#    url: jdbc:h2:mem:cdrdb
    url: jdbc:h2:file:./DB/cdrdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
#    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

server:
  error:
    whitelabel:
      enabled: false

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG